### DISCUSSION TITLE
Python Boost Library

### DISCUSSION THREAD

**Discussion by jonassorgenfrei** [MarkusJx/install-boost#25] [Q&A] [answered]
Hey i'm trying to use your action to build a test project against boost. 
Unfortunatly it looks like the boost python library is not build with it (?).

Using: 
find_package(Boost REQUIRED COMPONENTS python REQUIRED)
the return is:
`
 Found package configuration file:

    D:/a/PythonCLib/PythonCLib/boost/boost/lib/cmake/boost_python-1.78.0/boost_python-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND
`
The action I'm using is: 
https://github.com/jonassorgenfrei/PythonCLib/blob/main/.github/workflows/build-test-windows.yml

Is there a flag to configure the boost build to build the python lib too?

**Comment by MarkusJx** [comment]
All libraries except `msvc (shared)` and the arm libraries should support python. Try setting the `LINK` parameter to `static`.

If that doesn't work, I don't have any experience with the boost python libraries, maybe I'll need to configure the binaries differently?
But if that is the case, I can't promise anything as I'm building the binaries using github actions and the runners are already running low on memory, so adding more libraries to those binaries may not work at all (I had to disable python on arm due to memory issues already).

**Comment by jonassorgenfrei** [comment]
Hey @MarkusJx  thanks for your fast answer.

After adjusting my settings cmake now finds the libraries: 

```
    - name: Install boost
      uses: MarkusJx/install-boost@v2.3.1
      id: install-boost
      with:
          boost_version: 1.78.0
          link: static
          platform_version: 2022
          toolset: msvc
    #- name: Build Boost
    #  id: boost
    #  uses: egor-tensin/build-boost@v1
    #  with:
    #    version: 1.78.0
    #    libraries: system python
    #    platform: x64
    #    configuration: Release
    #    toolset: vs2022
    #    static: 1
    #- name: Show paths
    #  run: |
    #    echo 'Boost has been unpacked to: %s\n' '${{ steps.boost.outputs.root }}'
    #    echo 'Libraries can be found here: %s\n' '${{ steps.boost.outputs.librarydir }}'
    #  shell: bash
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -DBoost_USE_STATIC_LIBS=ON 
        # -D "BOOST_ROOT=${{ steps.boost.outputs.root }}"  -D "BOOST_LIBRARYDIR=${{ steps.boost.outputs.librarydir }}"
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: Build
      run: cmake --build build --parallel --config Release
```

Unfortunatly when building my project i do get now a lot of linking issues. 
```
myClass.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void * __cdecl boost::python::objects::find_static_type(void *,struct boost::python::type_info,struct boost::python::type_info)" (__imp_?find_static_type@objects@python@boost@@YAPEAXPEAXUtype_info@23@1@Z) referenced in function "private: virtual void * __cdecl boost::python::objects::value_holder<class MyClass>::holds(struct boost::python::type_info,bool)" (?holds@?$value_holder@VMyClass@@@objects@python@boost@@EEAAPEAXUtype_info@34@_N@Z) [D:\a\PythonCLib\PythonCLib\build\pyClass.vcxproj]
myClass.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl boost::python::converter::shared_ptr_deleter::shared_ptr_deleter(struct boost::python::converter::shared_ptr_deleter const &)" (__imp_??0shared_ptr_deleter@converter@python@boost@@QEAA@AEBU0123@@Z) referenced in function "public: __cdecl boost::detail::shared_count::shared_count<void *,struct boost::python::converter::shared_ptr_deleter>(void *,struct boost::python::converter::shared_ptr_deleter)" (??$?0PEAXUshared_ptr_deleter@converter@python@boost@@@shared_count@detail@boost@@QEAA@PEAXUshared_ptr_deleter@converter@python@2@@Z) [D:\a\PythonCLib\PythonCLib\build\pyClass.vcxproj]
    Hint on symbols that are defined and could potentially match:
      "__declspec(dllimport) public: __cdecl boost::python::converter::shared_ptr_deleter::shared_ptr_deleter(class boost::python::handle<struct _object>)" (__imp_??0shared_ptr_deleter@converter@python@boost@@QEAA@V?$handle@U_object@@@23@@Z)
myClass.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl boost::python::objects::py_function_impl_base::py_function_impl_base(void)" (__imp_??0py_function_impl_base@objects@python@boost@@QEAA@XZ) referenced in function "private: void __cdecl boost::python::class_<class MyClass,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified>::def_impl<class MyClass,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > (__cdecl*)(class MyClass const &),struct boost::python::detail::def_helper<char const *,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified> >(class MyClass *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > (__cdecl*)(class MyClass const &),struct boost::python::detail::def_helper<char const *,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified> const &,...)" (??$def_impl@VMyClass@@P6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV1@@ZU?$def_helper@PEBDUnot_specified@detail@python@boost@@U1234@U1234@@detail@python@boost@@@?$class_@VMyClass@@Unot_specified@detail@python@boost@@U2345@U2345@@python@boost@@AEAAXPEAVMyClass@@PEBDP6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV3@@ZAEBU?$def_helper@PEBDUnot_specified@detail@python@boost@@U1234@U1234@@detail@12@ZZ) [D:\a\PythonCLib\PythonCLib\build\pyClass.vcxproj]
myClass.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl boost::python::objects::class_base::~class_base(void)" (__imp_??1class_base@objects@python@boost@@QEAA@XZ) referenced in function "public: __cdecl boost::python::class_<class MyClass,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified>::~class_<class MyClass,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified>(void)" (??1?$class_@VMyClass@@Unot_specified@detail@python@boost@@U2345@U2345@@python@boost@@QEAA@XZ) [D:\a\PythonCLib\PythonCLib\build\pyClass.vcxproj]
myClass.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::objects::register_dynamic_id_aux(struct boost::python::type_info,struct std::pair<void *,struct boost::python::type_info> (__cdecl*)(void *))" (__imp_?register_dynamic_id_aux@objects@python@boost@@YAXUtype_info@23@P6A?AU?$pair@PEAXUtype_info@python@boost@@@std@@PEAX@Z@Z) referenced in function "void __cdecl boost::python::objects::register_dynamic_id<class MyClass>(class MyClass *)" (??$register_dynamic_id@VMyClass@@@objects@python@boost@@YAXPEAVMyClass@@@Z) [D:\a\PythonCLib\PythonCLib\build\pyClass.vcxproj]
myClass.obj : error LNK2001: unresolved external symbol "public: __cdecl boost::python::objects::class_base::~class_base(void)" (??1class_base@objects@python@boost@@QEAA@XZ) [D:\a\PythonCLib\PythonCLib\build\pyClass.vcxproj]
D:\a\PythonCLib\PythonCLib\build\Release\pyClass.pyd : fatal error LNK1120: 6 unresolved externals [D:\a\PythonCLib\PythonCLib\build\pyClass.vcxproj]
```

Locally i only tested with shared libraries not with static libraries

This is the Action I'm using which unfortunatly failed:
https://github.com/jonassorgenfrei/PythonCLib/actions/runs/3357491244/jobs/5563332782

**Comment by MarkusJx** [comment, marked as answer]
Apparently, the boost python libraries work in a weird way, so that's good to know.

I've tried compiling your project locally and found [this stackoverflow answer](https://stackoverflow.com/a/18111069). So for some reason, when using boost static libraries, you have to define `BOOST_PYTHON_STATIC_LIB` *before* including `boost/python.hpp`. So I've added this to your project and it compiles.

Thus, I present you two options solving your issue:
1. Define `BOOST_PYTHON_STATIC_LIB` in your `myClass.cpp` before including `boost/python.hpp`:
```c++
#define BOOST_PYTHON_STATIC_LIB
#include <boost/python.hpp>
```
2. (Probably more elegant) If you don't want to change your local setup, which you probably don't want to do, just add this to your `CMakeLists.txt`:
```cmake
# Use static python libs in CI runs
if(DEFINED ENV{CI})
    add_definitions(-DBOOST_PYTHON_STATIC_LIB)
endif()
```

Again, I can't provide shared boost libraries with python due to memory limitations, so these may be the only possible options.

Just let me know if this helped and have a nice day :)

**Reply by jonassorgenfrei** [reply]
Hey @MarkusJx 

thanks for your help, i see weired, i thought -DUSE_BOOST_STATIC would set the static libraries too. 

I adjusted my CMake to: 
```
if(Boost_USE_STATIC_LIBS)
    add_definitions(-DBOOST_PYTHON_STATIC_LIB)
endif()
```
So it always works when using Static Libs.

This morning i fought with making the action run on Linux too. 
Using Static Libs there too i got the following error: 
```
lib/libboost_python27-mt-d-x64.a(from_python.o): relocation R_X86_64_PC32 against symbol `PyExc_TypeError' can not be used when making a shared object; recompile with -fPIC
```
I'm not sure why the compilere uses the debug file (-d-x64) eventho i build as a release. 

After changing to shared libs on linux it worked like a charm!

There are only two questions open for me:
In your pre build libs you always only provide a lib for a specific python build is this random? Can you may be expose this version in the outputs? Is there the possibility to have multiple python versions supported per lib? 

When running my Actions i do get the following Warnings: 
`Starting install-boost@2.1.0
Downloading versions-manifest.json...
Parsing versions-manifest.json...
Warning: The parameter 'arch' was specified, which doesn't have any effect on this boost version
`

`
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
`
Are they important to care? Shall i create an Issue on this repo concerning them?

**Reply by MarkusJx** [reply]
Great to hear this finally works!

You should probably use shared libraries on linux as those are actually versioned in contrast to windows, providing a huge (size) benefit compared to static libs. And python shared libraries are provided by this action on linux so this is obviously not a problem.

As to your questions:
1. I guess the library is compiled against the installed python version on the runner. From the [docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software):

| Runner         | Python version   |
|----------------|------------------|
| Windows 2022   | 3.9.13           |
| Windows 2019   | 3.7.9            |
| Ubuntu 22.04.1 | 3.10.6           |
| Ubuntu 20.04.5 | 3.8.10           |
| macOS 11       | 3.10.8 or 2.7.18 |
| macOS 10.15    | 3.10.8 or 2.7.18 |
2. These are two separate things:
    2.1. You have the `arch` option specified, as this has no effect with you current boost version, you can omit that
    2.2. I've created a new issue for this: https://github.com/MarkusJx/install-boost/issues/26

**Reply by jonassorgenfrei** [reply]
Ah cool thanks for the information and help. 

Concerning 01: 
The docs show that the mentioned Python Versions are the prefered/newest ones. 
But there are mutliple versions installed e.g. 
    3.7.15
    3.8.14
    3.9.15
    3.10.8
Would it may be possible to provide the builds for all of the installed python versions? 
E.g. building the python libraries using the matrix strategy of the github actions? 
When i try to test my code using e.g. 3.7 on Windows 2022 it seems like the boost-python libs are refereing to python39.py. 
Otherwise i probably should check in my CMake file if the system's python verison is matching the build boost-python lib. 

Concerning 2.1:
In my Action Call i didn't set the arch parameter, do i specifically have to "unset" it or set it to 0 or None the code below is what i called:
```
- name: Install boost
      uses: MarkusJx/install-boost@v2.3.1
      id: install-boost
      with:
          boost_version: 1.78.0
          link: static
          platform_version: 2022
          toolset: msvc
```

Thanks for all your help :) !
