### DISCUSSION TITLE
CMake cannot find Boost on pybind11 package

### DISCUSSION THREAD

**Discussion by marcmgame** [MarkusJx/install-boost#40] [Q&A]
I am trying to use Boost on a pybind11 package, but GitHub actions fail because CMake cannot find Boost. Here is the [.yml](https://raw.githubusercontent.com/marcmgame/pybind11_boost_example/main/.github/workflows/build_wheels.yml) file. How can tell CMake where to find Boost for a Python package?

**Comment by MarkusJx** [comment]
Can you please provide the logs of your workflow run?

**Comment by marcmgame** [comment]
Here are the relevant part of the .yml file to build the wheels

```
      - name: Install boost on Windows
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost-windows
        with:
          boost_version: 1.78.0
          platform_version: 2019
          toolset: msvc
        if: runner.os == 'Windows'

      - name: Install boost on Linux
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost-linux
        with:
          boost_version: 1.80.0
          platform_version: 22.04
          toolset: gcc
          arch: x86
        if: runner.os == 'Linux'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_BUILD: cp${{ matrix.python }}-*
          # CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_MACOS: x86_64
          CIBW_ARCHS_LINUX: x86_64 # auto aarch64
```

Here are the relevant parts of the error message in Windows:

```
        CMake Error at C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-yovyy69h/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
          Could NOT find Boost (missing: Boost_INCLUDE_DIR regex date_time system
          filesystem thread graph program_options)
        Call Stack (most recent call first):
          C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-yovyy69h/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
          C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-yovyy69h/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/FindBoost.cmake:2392 (find_package_handle_standard_args)
          CMakeLists.txt:23 (find_package)
```

and on Linux

```
        CMake Error at /tmp/pip-build-env-x_cqsjq7/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
          Could NOT find Boost (missing: Boost_INCLUDE_DIR regex date_time system
          filesystem thread graph program_options)
        Call Stack (most recent call first):
          /tmp/pip-build-env-x_cqsjq7/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
          /tmp/pip-build-env-x_cqsjq7/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/FindBoost.cmake:2392 (find_package_handle_standard_args)
          CMakeLists.txt:23 (find_package)
```

The problem seems to be that `BOOST_ROOT` is empty and so `CMake` cannot find Boost.

Here is a link to the [repo](https://github.com/marcmgame/pybind11_boost_example.git) where I think you can see the full logs. Please look at the logs of the latest run.

**Reply by marcmgame** [reply]
It is possible (likely) that I am doing something wrong. So do you know of any examples (repos) that use `install-boost` with `cibuildwheels` to create multi-platform Python packages (preferably with `pybind11`)?

**Reply by MarkusJx** [reply]
Well, yes, `BOOST_ROOT` is empty by default, [you have to set it manually](https://github.com/MarkusJx/install-boost#boost_root):
```yml
- name: Install boost on Windows
   uses: MarkusJx/install-boost@v2.1.0
   id: install-boost
   with:
     boost_version: 1.78.0
      platform_version: 2019
      toolset: msvc
    if: runner.os == 'Windows'

- name: Install boost on Linux
   uses: MarkusJx/install-boost@v2.1.0
   id: install-boost
   with:
     boost_version: 1.80.0
     platform_version: 22.04
     toolset: gcc
     arch: x86
   if: runner.os == 'Linux'

- name: Build wheels
   uses: pypa/cibuildwheel@v2.11.4
   env:
     CIBW_BUILD: cp${{ matrix.python }}-*
     # CIBW_ARCHS_MACOS: x86_64 arm64
     CIBW_ARCHS_MACOS: x86_64
     CIBW_ARCHS_LINUX: x86_64 # auto aarch64
     BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
```

The important part is adding
```yml
BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
```
to the `env` flags of your build step

**Reply by MarkusJx** [reply]
If that still doesn't work, try setting the include and library directories:
```yml
env:
  Boost_INCLUDE_DIR: ${{steps.install-boost.outputs.BOOST_ROOT}}/include
  Boost_LIBRARY_DIRS: ${{steps.install-boost.outputs.BOOST_ROOT}}/lib
```
