### ISSUE TITLE
Error : Could not find boost version 1.77.0

### ISSUE THREAD

**Issue by gabriel654165** [MarkusJx/install-boost#10]
Hello !

I saw in your [manifest.json](https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json) that the 1.77.0 boost version was avalable.
I tried to use your Github action into mine with the following code : 
```yml
- name: Install boost
      if: ${{ matrix.os == 'windows-latest' }}
      uses: MarkusJx/install-boost@v2.1.0
      id: install-boost
      with:
        boost_version: 1.77.0
        boost_install_dir: ${{github.workspace}}
        platform_version: 2019
        toolset: msvc
```
But the github agent could not find a package version of boost 1.77.0 : 
```bash
Run MarkusJx/install-boost@v2.1.0
  with:
    boost_version: 1.77.0
    boost_install_dir: D:\a\zia\zia
    platform_version: 2019
    toolset: msvc
  env:
    BUILD_TYPE: Release
Starting install-boost@2.1.0
The install directory was manually changed to D:\a\zia\zia\boost
Downloading versions-manifest.json...
Parsing versions-manifest.json...
Error: Error: Could not find boost version 1.77.0
```
Do someone have an idea of what is going on with my code ?

Thanks a lot
