### ISSUE TITLE
Boost dlls 

### ISSUE THREAD

**Issue by dyollb** [MarkusJx/install-boost#11]
i was really pleased to find your repo. It makes installing boost for a cross-platform software really trivial. 
the only thing I miss is a version of boost for windows (2019) with DLLs.

any plans to add that flavor, or provide a build with both static and shared libs?

**Comment by MarkusJx** [comment]
I'll look into that, but this may take a while, so please be patient :).

**Comment by dyollb** [comment]
thanks. meanwhile I switched to using `egor-tensin/build-boost@v1`, which allows me to specify `static` vs `shared`.

**Comment by MarkusJx** [comment]
I've added shared libraries to the prebuilt binaries for windows, so you could try it out using the latest commit hash:
```yml
- name: Install boost
  uses: MarkusJx/install-boost@91f257c54ccc0ca4c5159edd1574f85945421973
  id: install-boost
  with:
    boost_version: 1.78.0.beta1
    toolset: msvc
    link: shared
    platform_version: 2019
```

This (currently) only works with boost version ``1.78.0.beta1``, but I could add more versions, if you need them. Also,
you can only select between static and shared libraries on windows, as the build runs out of memory when trying to build both at the same time. If you don't specify the ``link`` option, static libraries will be picked by default. If you need both static and shared libraries, you may just want to run the action twice, once specifying ``static`` link and the other time specifying ``shared`` link (make sure to adapt the output directories, though).

Please let me know if that works for you and if you have any further suggestions, just tell me :).
