### ISSUE TITLE
Use boost::filesystem on windows failed

### ISSUE THREAD

**Issue by MGuillaumeF** [MarkusJx/install-boost#15]
Hello,

when  add `find_package (Boost COMPONENTS system filesystem REQUIRED)` in my CMakeFile.txt, it's works well on MacOSX and Ubuntu in Job but failed with on Windows

(on local it works with the same CMakeList.txt windows)

The code in job :

```
 job-name:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        boost_version: ${{env.BOOST_VERSION}}
        platform_version: 2019
        boost_install_dir: 'D:/'
```

The error : 
```
CMake Error at D:/boost/boost/lib/cmake/Boost-1.79.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    D:/boost/boost/lib/cmake/boost_system-1.79.0/boost_system-config.cmake

  but it set boost_system_FOUND to FALSE so package "boost_system" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_system-mgw8-mt-d-x32-1_79.a (32 bit, need 64)

  * libboost_system-mgw8-mt-d-x64-1_79.a (mgw8, detected vc143, set
  Boost_COMPILER to override)
-- Configuring incomplete, errors occurred!

See also "D:/a/cpp-coso/cpp-coso/bin/CMakeFiles/CMakeOutput.log".
  * libboost_system-mgw8-mt-s-x32-1_79.a (32 bit, need 64)
See also "D:/a/cpp-coso/cpp-coso/bin/CMakeFiles/CMakeError.log".

  * libboost_system-mgw8-mt-s-x64-1_79.a (mgw8, detected vc143, set
  Boost_COMPILER to override)

  * libboost_system-mgw8-mt-sd-x32-1_79.a (32 bit, need 64)

  * libboost_system-mgw8-mt-sd-x64-1_79.a (mgw8, detected vc143, set
  Boost_COMPILER to override)

  * libboost_system-mgw8-mt-x32-1_79.a (32 bit, need 64)

  * libboost_system-mgw8-mt-x64-1_79.a (mgw8, detected vc143, set
  Boost_COMPILER to override)
```

I don't know if Windows need extra parameters to works with boost::filesystem usage, have you ever encountered this problem ?
