### ISSUE TITLE
Error with boost::system on Windows

### ISSUE THREAD

**Issue by MGuillaumeF** [MarkusJx/install-boost#16]
I have this error only on windows node (work in local)

```
Run cmake -S D:\a\cpp-coso\cpp-coso -B D:\a\cpp-coso\cpp-coso/bin -DCMAKE_BUILD_TYPE=Debug
-- Building for: Visual Studio 17 202
-- The C compiler identification is MSVC 19.32.31328.0
-- The CXX compiler identification is MSVC 19.32.31328.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Debug mode activate test
Compiler used is Microsoft Visual Studio C++
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE  
-- Found Boost: D:/boost/boost/lib/cmake/Boost-1.79.0/BoostConfig.cmake (found version "1.79.0") found components: system filesystem 
-- Configuring done

CMake Error in CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path
    "D:/boost/boost/include/boost-1_79"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not provide
```

With this job 
```
 job-name:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        boost_version: ${{env.BOOST_VERSION}}
        platform_version: 2022
        boost_install_dir: 'D:/'
        toolset: msvc
```
