### ISSUE TITLE
Could NOT find Boost (missing: system filesystem thread date_time chrono regex serialization program_options) (found version "1.74.0")

### ISSUE THREAD

**Issue by mjovanc** [MarkusJx/install-boost#24]
Not sure if I'm doing something wrong here. But Using the code below it simply cannot find Boost:

```yml
      - name: Install Dependencies
        if: matrix.config.os == 'windows-2019'
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Install boost
        uses: MarkusJx/install-boost@v2.3.1
        if: matrix.config.os == 'windows-2019'
        id: install-boost
        with:
            boost_version: 1.74.0
            boost_install_dir: C:\boost_1_74_0
            platform_version: 2019

      - name: Build windows Target using Visual C++
        if: matrix.config.os == 'windows-2019'
        run: |
          Get-ChildItem -Path ${{ steps.install-boost.outputs.BOOST_ROOT }}
          cmake . -G "Visual Studio 16 2019" -B build -DCMAKE_BUILD_TYPE=Release -DBoost_LIBRARY_DIRS=${{ steps.install-boost.outputs.BOOST_ROOT }}\lib -DBoost_INCLUDE_DIR=${{ steps.install-boost.outputs.BOOST_ROOT }}\include -DBOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
```

The error I get is:

```
-- The C compiler identification is MSVC 19.29.30146.0
-- The CXX compiler identification is MSVC 19.29.30146.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE  
CMake Warning (dev) at CMakeLists.txt:43 (set):
  implicitly converting 'TYPE' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.
-- FORCE_USE_HEAP: ENABLED

-- HW AES: ENABLED
-- OPTIMIZED_ARM_MULTIPLICATION: ENABLED
-- Found Git: C:/Program Files/Git/bin/git.exe
CMake Warning (dev) at CMakeLists.txt:261 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Boost_ROOT is set to:

    C:\boost_1_74_0\boost\boost

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1825 (file):
  file STRINGS file "C:\boost_1_74_0\boost\boost\include/boost/version.hpp"
  cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:261 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1015 (message):
  Imported targets and dependency information not available for Boost version
  0.0.0 (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1[50](https://github.com/kryptokrona/kryptokrona/actions/runs/3084897755/jobs/4987575888#step:5:51)7 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2118 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:261 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1015 (message):
  Imported targets and dependency information not available for Boost version
  0.0.0 (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1507 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2118 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:261 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1015 (message):
  Imported targets and dependency information not available for Boost version
  0.0.0 (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1507 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2118 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:261 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1015 (message):
  Imported targets and dependency information not available for Boost version
  0.0.0 (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1507 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2118 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:261 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1015 (message):
  Imported targets and dependency information not available for Boost version
  0.0.0 (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1507 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2118 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:261 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1015 (message):
  Imported targets and dependency information not available for Boost version
  0.0.0 (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1507 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2118 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:261 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1015 (message):
  Imported targets and dependency information not available for Boost version
  0.0.0 (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1507 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2118 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:261 (find_package)


CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: filesystem thread date_time chrono regex
-- Configuring incomplete, errors occurred!
See also "D:/a/kryptokrona/kryptokrona/build/CMakeFiles/CMakeOutput.log".
  serialization program_options) (found version "0.0.0")
See also "D:/a/kryptokrona/kryptokrona/build/CMakeFiles/CMakeError.log".
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:[59](https://github.com/kryptokrona/kryptokrona/actions/runs/3084897755/jobs/4987575888#step:5:60)4 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
  CMakeLists.txt:2[61](https://github.com/kryptokrona/kryptokrona/actions/runs/3084897755/jobs/4987575888#step:5:62) (find_package)
```
