### ISSUE TITLE
question: how to use this action when you have an OS matrix?

### ISSUE THREAD

**Issue by Ravenwater** [MarkusJx/install-boost#30]
My actions cover the os matrix [windows-latest, macos-latest, ubuntu-latest]

how do I use this action to support such a matrix OS workflow?

**Comment by MarkusJx** [comment]
The easiest way to accomplish this would be to use [multiple matrix configurations](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations):

```yml
jobs:
  build:
    runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          include:
            - os: ubuntu-22.04 # You should explicitly set the os version
              toolset: gcc     # The default toolset (this is explained in the readme)
              version: 22.04   # The reason why you should set the os version
            - os: windows-latest
              toolset: msvc
              version: 2022
            - os: macos-11
              toolset: clang
              version: 11

    steps:
      - uses: actions/checkout@v3
      - name: Install boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: 1.79.0
          platform_version: ${{matrix.version}}
          toolset: ${{matrix.toolset}}
      # Now you can continue as usual
```

You can also check my [`test-cmake` workflow](https://github.com/MarkusJx/install-boost/blob/main/.github/workflows/test-cmake.yml), which works in the same way.

**Comment by Ravenwater** [comment]
What am I doing wrong here?
![image](https://user-images.githubusercontent.com/466641/211052664-bd2e5af1-fe9f-4c34-9960-9f28d05b93f7.png)

**Comment by MarkusJx** [comment]
So this doesn't work as I thought, interesting. Just replace the version with the latest:
```yml
- name: Install boost
  uses: MarkusJx/install-boost@v2.4.3
```

**Comment by Ravenwater** [comment]
ok, that is looking good: 
![image](https://user-images.githubusercontent.com/466641/211053474-b1aaf258-7d72-4621-8684-f82281fd8510.png)

Now I am getting an error that cmake findpackage can't find boost because of a missing environment var:
![image](https://user-images.githubusercontent.com/466641/211053811-a8cb5378-a75f-4dfb-8cc6-34ef5ad09574.png)

This is code I am trying to revive after half a decade of neglect so this could be entirely my fault, but what is the design of 'install-boost' with respect to using findpackage to pick it up?

**Comment by MarkusJx** [comment]
As documented in the [Readme](https://github.com/MarkusJx/install-boost#outputs), just pass the boost root environment variable to the cmake configure step:
```yml
- name: Configure CMake
  run: cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B build
  env:
      BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
```
