### ISSUE TITLE
x64 platform

### ISSUE THREAD

**Issue by damian123** [MarkusJx/install-boost#36]
Thank you for a great install package!!

Do you have any plans to support x64 platforms?

**Comment by MarkusJx** [comment]
x64 platforms *should* be supported, both linux and macOs images ship just with x64 binaries, windows images come with support for both x32 and x64.

Is there any specific configuration that's not working for you?

**Comment by MGuillaumeF** [comment]
Hello, packages works well with x64 platforms, but on Linux with arch x32 i have an error 

The error :

```
usr/bin/ld: i386:x86-64 architecture of input file `/home/runner/work/cpp-coso/cpp-coso/boost/boost/lib/libboost_filesystem-mt-x64.a(operations.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/home/runner/work/cpp-coso/cpp-coso/boost/boost/lib/libboost_filesystem-mt-x64.a(path.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/home/runner/work/cpp-coso/cpp-coso/boost/boost/lib/libboost_filesystem-mt-x64.a(unique_path.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/home/runner/work/cpp-coso/cpp-coso/boost/boost/lib/libboost_filesystem-mt-x64.a(exception.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/home/runner/work/cpp-coso/cpp-coso/boost/boost/lib/libboost_filesystem-mt-x64.a(directory.o)' is incompatible with i386 output
/usr/bin/ld: /home/runner/work/cpp-coso/cpp-coso/boost/boost/lib/libboost_filesystem-mt-x64.a(path.o): in function `boost::filesystem::path::codecvt() [clone .cold]':
…
```

The use of package :
```
  build-release-Linux:
    runs-on: ubuntu-latest
    steps:

    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.4
      id: install-boost
      with:
        boost_version: 1.81.0
        platform_version: 20.04
```
