### ISSUE TITLE
Header Only installation.

### ISSUE THREAD

**Issue by weinbe58** [MarkusJx/install-boost#41]
Hello! I like this action; it will be super helpful for my project; however, my project only needs the header files from Boost to work, and for some reason, my current build workflow doesn't like the extra binary files generated by this action.

I can probably remove the extra binary files in my action, but having a header-only installation would be great!

Thanks!

**Comment by MarkusJx** [comment]
The easiest way to achieve this would probably be by simply downloading and extracting the binary:
```yml
name: Build

on:
  push:
  pull_request:

env:
  BOOST_VERSION: 1.84.0
  # The version with underscores instead of dots, you could also use a bash script for this
  BOOST_DIR_VER_NAME: 1_84_0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Use a cache for increased performance
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v3
        with:
          path: include/boost
          key: ${{ runner.os }}-boost
      - name: Download boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/${{env.BOOST_VERSION}}/source/boost_${{env.BOOST_DIR_VER_NAME}}.tar.gz
          tar xzf boost_${{env.BOOST_DIR_VER_NAME}}.tar.gz
          mkdir include
          mv boost_${{env.BOOST_DIR_VER_NAME}}/boost include/boost
```

Although I have not tested this, it should work just fine (maybe the environment variables are not used correctly, but I'm confident you'll figure it out). Anyways, I hope this fits your needs as this actions focus is on prebuilt boost binaries and not just downloading and unzipping the tarballs. If this doesn't help, let me know and I'll see if i can include a non-prebuilt option in this action.
